import { sendEmail } from "@/lib/emails/send-email";

/**
 * Payload parameters required to dispatch an email address verification message.
 *
 * @author Maruf Bepary
 */
interface EmailVerificationData {
  /** Target recipient user details. */
  user: {
    /** Display name of the user receiving the verification email. */
    name: string;
    /** Destination email address to verify. */
    email: string;
  };
  /** Secure verification link containing Better Auth validation token. */
  url: string;
}

/**
 * Dispatches an email address verification message through Postmark.
 * Invoked during user registration or email address change flows in Better Auth
 * to confirm ownership of the specified email address.
 * Generates both responsive HTML and plain-text fallback representations containing the expiration warning.
 *
 * @param data - Verification email payload containing recipient details and callback URL
 * @param data.user - Recipient user profile information
 * @param data.url - One-time verification link generated by Better Auth
 * @returns Promise resolving upon successful message transmission
 * @throws {Error} When Postmark fails to deliver the verification email
 * @see sendEmail for the underlying Postmark email delivery mechanism
 * @author Maruf Bepary
 */
export async function sendEmailVerificationEmail({
  user,
  url,
}: EmailVerificationData) {
  await sendEmail({
    to: user.email,
    subject: "Verify your email address",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333;">Verify Your Email</h2>
        <p>Hello ${user.name},</p>
        <p>Thank you for signing up! Please verify your email address by clicking the button below:</p>
        <a href="${url}" style="background-color: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block; margin: 16px 0;">Verify Email</a>
        <p>If you didn't create an account, please ignore this email.</p>
        <p>This link will expire in 24 hours.</p>
        <p>Best regards,<br>Your App Team</p>
      </div>
    `,
    text: `Hello ${user.name},\n\nThank you for signing up! Please verify your email address by clicking this link: ${url}\n\nIf you didn't create an account, please ignore this email.\n\nThis link will expire in 24 hours.\n\nBest regards,\nYour App Team`,
  });
}
