import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ImpersonationIndicator } from "@/components/auth/impersonation-indicator";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Default global application metadata configuration for SEO and browser tab titles.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root application layout component wrapping all routes in the Next.js App Router.
 * Operates as a React Server Component (RSC) to establish the HTML shell, configure Google Fonts
 * (Geist and Geist Mono font variables), enforce a default dark theme styling, and mount
 * cross-application interactive utilities such as Sonner toasts and an impersonation warning banner.
 *
 * @param props - Root layout properties containing child route content
 * @returns Root HTML document structure enclosing all nested page components
 * @author Maruf Bepary
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark flex justify-center antialiased`}
      >
        <div className="w-3xl">
          {children}
          <Toaster position="top-left" />
          <ImpersonationIndicator />
        </div>
      </body>
    </html>
  );
}
