"use client";

import { useEffect, useRef, useState } from "react";
import { BetterAuthActionButton } from "@/components/auth/better-auth-action-button";
import { ROUTES } from "@/config/routes";
import { authClient } from "@/lib/auth/auth-client";

/**
 * Email verification status view with an automated cooldown resend mechanism.
 * Executes as a Client Component ("use client") integrating with Better Auth client verification endpoints
 * and maintaining client-side throttling to mitigate email spam and provider rate limits.
 *
 * Security Context & Flow:
 * - Directs the user to inspect their inbox for the verification token URL generated by Better Auth.
 * - Enforces an active 30-second cooldown period upon component mount and subsequent resend requests.
 * - Triggers `authClient.sendVerificationEmail` with `ROUTES.HOME` as the post-verification landing URL.
 * - Disables the action button during the countdown, giving live visual feedback of the remaining cooldown seconds.
 *
 * @param props - Component properties containing the recipient email address
 * @returns Client-rendered verification prompt card with throttled resend button
 * @author Maruf Bepary
 */
export function EmailVerification({ email }: { email: string }) {
  const [timeToNextResend, setTimeToNextResend] = useState(30);
  const interval = useRef<NodeJS.Timeout>(undefined);

  /**
   * Initializes or restarts the countdown timer to prevent rapid email resend requests.
   *
   * @param time - Cooldown duration in seconds before allowing another email dispatch
   * @author Maruf Bepary
   */
  function startEmailVerificationCountdown(time = 30) {
    setTimeToNextResend(time);

    clearInterval(interval.current);
    interval.current = setInterval(() => {
      setTimeToNextResend((t) => {
        const newT = t - 1;

        if (newT <= 0) {
          clearInterval(interval.current);
          return 0;
        }
        return newT;
      });
    }, 1000);
  }

  // biome-ignore lint/correctness/useExhaustiveDependencies: Initial countdown setup on mount is intentional
  useEffect(() => {
    startEmailVerificationCountdown();
  }, []);

  return (
    <div className="space-y-4">
      <p className="mt-2 text-muted-foreground text-sm">
        We sent you a verification link. Please check your email and click the
        link to verify your account.
      </p>

      <BetterAuthActionButton
        variant="outline"
        className="w-full"
        successMessage="Verification email sent!"
        disabled={timeToNextResend > 0}
        action={() => {
          startEmailVerificationCountdown();
          return authClient.sendVerificationEmail({
            email,
            callbackURL: ROUTES.HOME,
          });
        }}
      >
        {timeToNextResend > 0
          ? `Resend Email (${timeToNextResend})`
          : "Resend Email"}
      </BetterAuthActionButton>
    </div>
  );
}
