import z from "zod";

/**
 * Validation schema for confirming TOTP authenticator setup via QR code.
 * Used during the two-factor authentication onboarding flow to verify the first TOTP code
 * generated by the user's authenticator app scanning the setup QR code.
 * Enforces an exact 6-character token length required to complete 2FA activation.
 *
 * @author Maruf Bepary
 */
export const qrSchema = z.object({
  token: z.string().length(6),
});

/**
 * Inferred TypeScript type representing valid QR code verification form values.
 * Used for typed form state and submission handling in 2FA QR enrollment dialogs.
 *
 * @author Maruf Bepary
 */
export type QrForm = z.infer<typeof qrSchema>;
